import { Meta, StoryFn } from '@storybook/react';
import React from 'react';
import {
  MetadataKeyValueList,
  MetadataKeyValueListProps
} from "../../../components/elements/MetadataKeyValue/MetadataKeyValueList";

const meta: Meta<MetadataKeyValueListProps> = {
  title: 'Elements/MetadataKeyValueList',
  component: MetadataKeyValueList
};

export default meta;

const Template: StoryFn<typeof MetadataKeyValueList> = (args) => (
  <MetadataKeyValueList {...args} />
);

export const ControlledDisplayFilterBasic: StoryFn<typeof MetadataKeyValueList> =
  Template.bind({});
ControlledDisplayFilterBasic.args = {
  metadataList:
  [
    {key: "key1", value: "mockValue1", valueType: "string", multiple:false },
    {key: "key2", value: "42", valueType: "number" , isAutoGenerated:true, multiple:false},
    {key: "key3", value: "true", valueType: "boolean", multiple:false },
  ]
};
