import { Meta, StoryFn } from '@storybook/react';
import React from 'react';
import SingleFileViewModal, {
  ItemData,
  singleFileViewModalProps
} from '../../../../components/dagshub/data-engine/singleFileViewModal/SingleFileViewModal';
import { NewMetadataField } from '../../../../components';
import { Button } from '@mui/material';

const meta: Meta<singleFileViewModalProps> = {
  title: 'DagsHub/Data-Engine/Modals/Single file view modal',
  component: SingleFileViewModal
};

export default meta;

const itemDataMockList: ItemData[] = [
  {
    itemIndex: 0,
    itemType: 'image',
    repoFilePath:
      'https://dagshub.com/Simon/baby-yoda-segmentation-dataset/src/master/images/007.png',
    galleryFilePath:
      'https://dagshub.com/Simon/baby-yoda-segmentation-dataset/raw/master/images/007.png',
    fileName: '007.png',
    metadataList: [{ key: 'size', value: '123456', valueType: 'INTEGER', isAutoGenerated: true }],
    hasPrevious: false,
    hasNext: true
  },
  {
    itemIndex: 1,
    itemType: 'audio',
    repoFilePath:
      'https://dagshub.com/DAGsHub-Official/annotations-showcase/src/main/data/audio/abc.wav',
    galleryFilePath:
      'https://dagshub.com/DAGsHub-Official/annotations-showcase/raw/main/data/audio/abc.wav',
    fileName: 'abc.wav',
    metadataList: [
      { key: 'size', value: '34567899', valueType: 'INTEGER', isAutoGenerated: true },
      { key: 'is_cat', value: 'false', valueType: 'BOOLEAN' },
      { key: 'is_earth_space', value: 'true', valueType: 'BOOLEAN' },
      { key: 'is_video', value: 'true', valueType: 'BOOLEAN' },
      { key: 'length', value: '16 seconds', valueType: 'STRING' },
      { key: 'description', value: 'this is a video about earth space', valueType: 'STRING' },
      { key: 'categories', value: 'earth, space, live, human', valueType: 'INTEGER' }
    ],
    hasPrevious: true,
    hasNext: true
  },
  {
    itemIndex: 2,
    itemType: 'video',
    repoFilePath:
      'https://dagshub.com/DAGsHub-Official/annotations-showcase/src/main/data/videos/earth-space-small.mp4',
    galleryFilePath:
      'https://dagshub.com/DAGsHub-Official/annotations-showcase/raw/main/data/videos/earth-space-small.mp4',
    fileName: 'earth-space-small.mp4',
    metadataList: [
      { key: 'size', value: '3456789', valueType: 'INTEGER', isAutoGenerated: true },
      { key: 'is_cat', value: 'false', valueType: 'BOOLEAN' },
      { key: 'is_earth_space', value: 'true', valueType: 'BOOLEAN' },
      { key: 'is_video', value: 'true', valueType: 'BOOLEAN' },
      { key: 'length', value: '16 seconds', valueType: 'STRING' },
      { key: 'description', value: 'this is a video about earth space', valueType: 'STRING' },
      { key: 'categories', value: 'earth, space, live, human', valueType: 'INTEGER' }
    ],
    hasPrevious: true,
    hasNext: true
  },
  {
    itemIndex: 3,
    itemType: 'image',
    repoFilePath: 'https://dagshub.com/Dean/COCO_1K/src/main/data/images/train/000000001681.jpg',
    galleryFilePath: 'https://dagshub.com/Dean/COCO_1K/raw/main/data/images/train/000000001681.jpg',
    fileName: '000000001681.jpg',
    metadataList: [{ key: 'size', value: '34567878', valueType: 'INTEGER', isAutoGenerated: true }],
    hasPrevious: true,
    hasNext: true
  },
  {
    // Using local file cause otherwise im getting CORS error
    itemIndex: 4,
    itemType: 'text',
    repoFilePath: '/assets/textFile.txt',
    galleryFilePath: '/assets/textFile.txt',
    fileName: 'textFile.txt',
    metadataList: [{ key: 'size', value: '34567890', valueType: 'INTEGER', isAutoGenerated: true }],
    hasPrevious: true,
    hasNext: true
  },
  {
    // Using local file cause otherwise im getting CORS error
    itemIndex: 5,
    itemType: 'pdf',
    repoFilePath: '/assets/2019-Sem-B-Moed-B.pdf',
    galleryFilePath: '/assets/2019-Sem-B-Moed-B.pdf',
    fileName: '2019-Sem-B-Moed-B.pdf',
    metadataList: [{ key: 'size', value: '34567890', valueType: 'INTEGER', isAutoGenerated: true }],
    hasPrevious: true,
    hasNext: true
  },
  {
    // Using local file cause otherwise im getting CORS error
    itemIndex: 6,
    itemType: 'pdf',
    repoFilePath: '/assets/2019-Sem-B-Moed-A.pdf',
    galleryFilePath: '/assets/2019-Sem-B-Moed-A.pdf',
    fileName: '2019-Sem-B-Moed-A.pdf',
    metadataList: [{ key: 'size', value: '34567891', valueType: 'INTEGER', isAutoGenerated: true }],
    hasPrevious: true,
    hasNext: true
  },
  {
    itemIndex: 7, // expect to get n error fallback
    itemType: 'image',
    repoFilePath:
        'https://dagshub.com/Simon/baby-yoda-segmentation-datasett/src/master/images/007.png',
    galleryFilePath:
        'https://dagshub.com/Simon/baby-yoda-segmentation-datasett/raw/master/images/007.png',
    fileName: '007.png- wrong url',
    metadataList: [{ key: 'size', value: '123456', valueType: 'INTEGER', isAutoGenerated: true }],
    hasPrevious: false,
    hasNext: true
  },
  {
    itemIndex: 8,
    itemType: 'na',
    repoFilePath:
      'https://dagshub.com/DAGsHub-Official/annotations-showcase/src/main/data/tabular/housing.csv',
    galleryFilePath:
      'https://dagshub.com/DAGsHub-Official/annotations-showcase/raw/main/data/tabular/housing.csv',
    fileName: 'housing.csv',
    metadataList: [
      { key: 'size', value: '345678', valueType: 'INTEGER', isAutoGenerated: true },
      { key: 'is_cat', value: 'false', valueType: 'BOOLEAN' },
      { key: 'is_earth_space', value: 'true', valueType: 'BOOLEAN' },
      { key: 'is_video', value: 'true', valueType: 'BOOLEAN' },
      { key: 'length', value: '16 seconds', valueType: 'STRING' },
      { key: 'description', value: 'this is a video about earth space', valueType: 'STRING' },
      { key: 'categories', value: 'earth, space, live, human', valueType: 'INTEGER' }
    ],
    hasPrevious: true,
    hasNext: false
  }
];

const Template: StoryFn<typeof SingleFileViewModal> = (args) => {
  const [currentItemData, setCurrentItemData] = React.useState<ItemData>(itemDataMockList[0]);
  const [isModalOpen, setIsModalOpen] = React.useState<boolean>(true);
  return (
    <>
      {isModalOpen ? (
        <SingleFileViewModal
          {...args}
          closeModal={() => {
            setIsModalOpen(false);
          }}
          itemData={currentItemData}
          onGetNextItemClickHandler={() => {
            setCurrentItemData(itemDataMockList[currentItemData.itemIndex + 1]);
          }}
          onGetPreviousItemClickHandler={() => {
            setCurrentItemData(itemDataMockList[currentItemData.itemIndex - 1]);
          }}
          enableDatapointAnnotating={true}
          enableFileDownloading={true}
          onAnnotatedClick={() => {
            console.log('annotated');
          }}
        />
      ) : (
        <Button onClick={() => setIsModalOpen(true)}>Open modal</Button>
      )}
    </>
  );
};

export const singlefileViewModalWithEditingEnabled: StoryFn<typeof SingleFileViewModal> =
  Template.bind({});

singlefileViewModalWithEditingEnabled.args = {
  enableMetadataEditing: true,
  enableMetadataDeletion: true,
  metadataOnChangeHandler: (metadataList: NewMetadataField[]) => {
    // console.log(metadataList)
  }
};

export const singlefileViewModal: StoryFn<typeof SingleFileViewModal> = Template.bind({});

singlefileViewModal.args = {};
