import React from 'react';
import Box from "@mui/material/Box";
import {MetadataKeyValuePair} from "./MetadataKeyValuePair";

export interface MetadataKeyValueListProps {
    maxKeySectionHeight?: string;
    metadataList:Record<string, { value: string; valueType: string ; isAutoGenerated?: boolean}>;
    isEditable:boolean;
    onSaveHandler?:()=>void;
}

export function MetadataKeyValueList({
                                                  maxKeySectionHeight,
                                                  metadataList,
                                                  isEditable,
                                                  onSaveHandler
                                              }: MetadataKeyValueListProps) {

    //need to hold some shallow copy, and to have on change function that I pass down , which should update it
    //In addition, if editable, I should add some section which add new button and a new line added that enables you to select the type
    //need to have save button
    //on save i should refetch the metadata
    const newMetadataList:Record<string, { value: string; valueType: string ; isAutoGenerated?: boolean}>={};


    //need to have some type validation, and some error insication in case the save buton failes
    return (
        <Box sx={{maxHeight:maxKeySectionHeight, overflowY:"auto"}}>
            {Object.keys(metadataList).map((key) => (
                <MetadataKeyValuePair {...metadataList[key]} keyName={key} isEditable={isEditable} />
            ))}
            <MetadataKeyValuePair keyName={""} isEditable={isEditable} isNewlyCreated={true} value={""} valueType={"string"}/>
        </Box>
    );
}
