import React from 'react';
import { Meta, StoryFn } from '@storybook/react';
import { CustomAccordion, MetadataKeyValueList } from '../../../components';

const meta: Meta<typeof CustomAccordion> = {
  title: 'Elements/CustomAccordion',
  component: CustomAccordion,
};

export default meta;

const Template: StoryFn<typeof CustomAccordion> = (args) => <CustomAccordion {...args} />;

export const customAccordion: StoryFn<typeof CustomAccordion> = Template.bind({});
customAccordion.args = {
  label: 'Metadata',
  children: (
    <MetadataKeyValueList
      metadataList={[
        { key: 'size', value: '345678', valueType: 'INTEGER', isAutoGenerated: true },
        { key: 'is_cat', value: 'false', valueType: 'BOOLEAN' },
        { key: 'is_earth_space', value: 'true', valueType: 'BOOLEAN' },
        { key: 'is_video', value: 'true', valueType: 'BOOLEAN' },
        { key: 'length', value: '16 seconds', valueType: 'STRING' },
        { key: 'description', value: 'this is a video about earth space', valueType: 'STRING' },
        { key: 'categories', value: 'earth, space, live, human', valueType: 'INTEGER' },
      ]}
      editingEnabled={true}
      deletionEnabled={false}
      onChangeHandler={() => {}}
    />
  ),
};
