name: License check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: dagshub/node-license-checker-action@v1
      env:
        EXCLUDE_PACKAGES: rollup-plugin-dts

    - run: |
        commit="$GITHUB_SHA"
        base_link="github.com/$GITHUB_REPOSITORY"
        date=`date "+%B %e %Y"`
        awk -F',' -v "commit=$commit" -v "base_link=$base_link" -v "date=$date" '{OFS=","; print base_link,commit,date,$1,$2,$3}' licenses.csv > all-licenses.csv
    
    - name: Upload unified license report
      uses: actions/upload-artifact@v3
      with:
        name: all-licenses.csv
        path: all-licenses.csv
        if-no-files-found: error
